@startuml

actor Client
Client -> ProxyMiddleware : HTTP request
ProxyMiddleware -> ProxyRequestUseCase : execute()

ProxyRequestUseCase -> BRSParser : parse()
ProxyRequestUseCase -> ChooseNodeUseCase : execute()

ChooseNodeUseCase -> MetricsRepository : list_latest()
ChooseNodeUseCase -> DecisionResolverPolicy
DecisionResolverPolicy -> RankingStrategy
DecisionResolverPolicy -> WeightsStrategy

"MCDM Strategy" --> ChooseNodeUseCase : scores
ChooseNodeUseCase --> ProxyRequestUseCase : node

alt replication
    ProxyRequestUseCase -> ReplicationManager
    ReplicationManager -> ReplicationPlanner
    ReplicationPlanner -> ReplicationStrategy
    ReplicationManager -> ReplicationRunner
    ReplicationRunner -> CompletionPolicy
end

ProxyRequestUseCase -> TargetNode : HTTP call
TargetNode --> ProxyRequestUseCase : response
ProxyRequestUseCase -> MetricsRepository : add_latency()

ProxyRequestUseCase --> ProxyMiddleware : result
ProxyMiddleware --> Client : HTTP response

@enduml